language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
    - shards
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_SHARDS_DIR=shards
    - BINARYBUILDER_AUTOMATIC_APPLE=true
    - BINARYBUILDER_USE_CCACHE=true
  # Our build takes too long for one job, so split targets across multiple jobs
  matrix:
    - TARGET=x86_64-linux-gnu
    - TARGET=i686-linux-gnu
    - TARGET=aarch64-linux-gnu
    - TARGET=arm-linux-gnueabihf
    - TARGET=powerpc64le-linux-gnu
    - TARGET=x86_64-apple-darwin14
    - TARGET=x86_64-w64-mingw32
    - TARGET=i686-w64-mingw32
sudo: required

jobs:
  include:
    - stage: regenerate build.jl
      script: julia --color=yes build_tarballs.jl --only-buildjl
      if: tag IS present

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'

script:
  - julia build_tarballs.jl --llvm-reldbg --llvm-keep-tblgen $TARGET
  - julia build_tarballs.jl --llvm-release $TARGET

deploy:
  provider: releases
  api_key:
    # Note; this api_key is only valid for staticfloat/LLVMBuilder; you need
    # to make your own: https://docs.travis-ci.com/user/deployment/releases/
    secure: d/nKMKzsPJCRxzzYWY3ioZHZ4vHR0KxW5kua9zLG5P9Ul4AZm/H1wB1El+R/dtitXyWLleQL6+svtIT+FJNzgzLif1ZENg1cK4mKsF/UERsuT0UH9w6fAOAWvkn1RWNkKn72nkINPs3jIUT6t85aRDkO25MpVN0NU0PRPrX4nsBQSabJRm1ZLENAgLJhEK5uLMfLC7cc2nFobEOvsnALsHWr0grSZBDGKlnPC0gQ1jUD7CCUb9jS+LFWy5WeVO7JuQKu71wCKvjPzqz0RI4rdnuKJGsj2+3hvUPWxn4d+d3YA2+vQ9WzWlrFWcgBTQk0H/RSYZEW2d6bgDm7bB3QFVvrhoDSPUNhNmAzEzCl9Mki1ffWVi4O2lEUXXWSISxkUf0SwfH/SIvYOvj9Quh3au3c8Ks1JMBKTi1yENVSzbZnLbJCPQBeubfeyfI2hWczccA4XN/skTB85aO5xcFgKP1Nd8otiqkuo05VglAH+PyC2Z0mRHTfMS48ZR6i7ZSxyuyWjap8HRGar9Urk016ocsgtAUj8DX3nA2yOWUFwv0CvGskQi8gx2GoK2+B5/U+iqqQmqYK47CV04bet9p8wezdwyZiiUh67btpT4ol6WXYWbV5mtYAHldb+FwRn/Cxd9BNtEQjpmHQFieE/52TpzqJq2Pbq1PiPdn/d6Fnwac=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: staticfloat/LLVMBuilder
    tags: true
